-- Run once in the Supabase SQL editor.
-- The upload page remains functional before this migration is applied; it simply
-- skips learning-history writes until this table exists.

create table if not exists public.product_image_ai_reviews (
  id bigint generated by default as identity primary key,
  item_code text not null,
  item_name text,
  brand text,
  decision text not null check (decision in ('accepted', 'rejected', 'ai_blocked', 'generated_accepted')),
  source_type text not null check (source_type in ('catalogue_crop', 'official_url', 'ai_generated', 'manual')),
  image_url text,
  image_sha256 text,
  catalogue_page integer,
  catalogue_code text,
  catalogue_confidence numeric(5,4),
  verification_verdict text,
  verification_confidence numeric(5,4),
  web_supported boolean not null default false,
  official_source_found boolean not null default false,
  verification_reason text,
  hard_conflicts jsonb not null default '[]'::jsonb,
  matched_attributes jsonb not null default '[]'::jsonb,
  evidence_sources jsonb not null default '[]'::jsonb,
  visual_observation jsonb not null default '{}'::jsonb,
  model_name text,
  reviewed_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);

create index if not exists product_image_ai_reviews_item_code_idx
  on public.product_image_ai_reviews (item_code, created_at desc);

create index if not exists product_image_ai_reviews_image_sha256_idx
  on public.product_image_ai_reviews (image_sha256)
  where image_sha256 is not null;

alter table public.product_image_ai_reviews enable row level security;

drop policy if exists "Authenticated users can read product image AI reviews"
  on public.product_image_ai_reviews;
drop policy if exists "Authenticated users can create product image AI reviews"
  on public.product_image_ai_reviews;

-- Intentionally no browser-facing policies. Review reads/writes go through
-- server.js, whose service-role/secret key bypasses RLS after validating the
-- user's login token against the primary Supabase project.

comment on table public.product_image_ai_reviews is
  'Human and AI decisions used to audit and improve product image catalogue matching.';
