-- Run this once in the Supabase SQL editor for the primary Vajra project.
create table if not exists public.website_enquiries (
  id bigint generated by default as identity primary key,
  customer_name text,
  mobile text not null,
  note text,
  items jsonb not null default '[]'::jsonb,
  item_count integer not null default 0,
  estimated_total numeric(14,2) not null default 0,
  status text not null default 'new' check (status in ('new','contacted','closed','cancelled')),
  source text not null default 'website',
  notified_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists website_enquiries_created_at_idx on public.website_enquiries (created_at desc);
create index if not exists website_enquiries_mobile_idx on public.website_enquiries (mobile);
create index if not exists website_enquiries_status_idx on public.website_enquiries (status);

alter table public.website_enquiries enable row level security;

-- Public visitors can submit, but cannot read, change, or delete any enquiry.
grant insert on table public.website_enquiries to anon, authenticated;
grant usage, select on sequence public.website_enquiries_id_seq to anon, authenticated;
grant select on table public.website_enquiries to authenticated;

drop policy if exists "public can submit website enquiries" on public.website_enquiries;
create policy "public can submit website enquiries"
on public.website_enquiries for insert
to anon, authenticated
with check (
  status = 'new'
  and source = 'website'
  and char_length(mobile) between 10 and 15
  and item_count between 1 and 99999
  and jsonb_typeof(items) = 'array'
  and jsonb_array_length(items) between 1 and 100
);

drop policy if exists "approved managers can view website enquiries" on public.website_enquiries;
create policy "approved managers can view website enquiries"
on public.website_enquiries for select
to authenticated
using (
  exists (
    select 1 from public.user_profiles profile
    where profile.id = auth.uid()
      and profile.approved = true
      and upper(coalesce(profile.role, '')) in ('OWNER', 'ADMIN', 'MANAGER')
  )
);
