-- Run once in the Supabase SQL editor.
create table if not exists public.bill_edit_grants (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.user_profiles(id) on delete cascade,
  granted_by uuid not null references public.user_profiles(id),
  grant_type text not null check (grant_type in ('single','bill_range','date_range','month')),
  series_code text,
  bill_from bigint,
  bill_to bigint,
  date_from date,
  date_to date,
  month_value text check (month_value is null or month_value ~ '^\\d{4}-\\d{2}$'),
  used_at timestamptz,
  used_sale_id bigint,
  created_at timestamptz not null default now(),
  check (bill_from is null or bill_to is null or bill_from <= bill_to),
  check (date_from is null or date_to is null or date_from <= date_to)
);

alter table public.bill_edit_grants enable row level security;

create policy "Admins manage bill edit grants" on public.bill_edit_grants
for all to authenticated using (
  exists (select 1 from public.user_profiles p where p.id=auth.uid() and upper(p.role) in ('OWNER','ADMIN'))
) with check (
  exists (select 1 from public.user_profiles p where p.id=auth.uid() and upper(p.role) in ('OWNER','ADMIN'))
);

create policy "Users read own bill edit grants" on public.bill_edit_grants
for select to authenticated using (user_id=auth.uid());

create or replace function public.get_bill_edit_grant(p_sale_id bigint)
returns table(allowed boolean, grant_id bigint) language sql security definer set search_path=public as $$
  select true, g.id from sales_details s join bill_edit_grants g on g.user_id=auth.uid() and g.used_at is null
  where s.id=p_sale_id and (
    (g.grant_type in ('single','bill_range') and (g.series_code is null or g.series_code=s.series_code)
      and s.sales_number::bigint between g.bill_from and g.bill_to)
    or (g.grant_type='date_range' and s.bill_date between g.date_from and g.date_to)
    or (g.grant_type='month' and to_char(s.bill_date,'YYYY-MM')=g.month_value)
  ) order by g.created_at limit 1;
$$;

create or replace function public.consume_bill_edit_grant(p_grant_id bigint, p_sale_id bigint)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  update bill_edit_grants set used_at=now(), used_sale_id=p_sale_id
  where id=p_grant_id and user_id=auth.uid() and used_at is null
    and exists (select 1 from get_bill_edit_grant(p_sale_id) x where x.grant_id=p_grant_id);
  return found;
end; $$;

revoke all on function public.get_bill_edit_grant(bigint) from public;
revoke all on function public.consume_bill_edit_grant(bigint,bigint) from public;
grant execute on function public.get_bill_edit_grant(bigint) to authenticated;
grant execute on function public.consume_bill_edit_grant(bigint,bigint) to authenticated;
