-- Run once in the Supabase SQL editor. Damage entries are deliberately separate
-- from stock_items and stock_ledger, so saving or solving damage never adjusts stock.
create table if not exists public.damage_entries (
  id bigint generated by default as identity primary key,
  damage_date date not null default current_date,
  item_code text not null,
  item_name text not null,
  quantity numeric(14,3) not null check (quantity > 0),
  supplier_name text,
  reference_no text,
  reason text,
  remark text,
  status text not null default 'OPEN' check (status in ('OPEN','SOLVED')),
  resolution_type text check (resolution_type is null or resolution_type in ('REPLACEMENT','CREDIT NOTE','SERVICE','OTHER')),
  resolution_note text,
  solved_at timestamptz,
  solved_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) default auth.uid()
);

create index if not exists damage_entries_item_status_idx
  on public.damage_entries (item_code, status);
create index if not exists damage_entries_date_idx
  on public.damage_entries (damage_date desc);

alter table public.damage_entries enable row level security;

drop policy if exists "authenticated users read damages" on public.damage_entries;
create policy "authenticated users read damages" on public.damage_entries
  for select to authenticated using (true);
drop policy if exists "authenticated users add damages" on public.damage_entries;
create policy "authenticated users add damages" on public.damage_entries
  for insert to authenticated with check (created_by = auth.uid());
drop policy if exists "authenticated users solve damages" on public.damage_entries;
create policy "authenticated users solve damages" on public.damage_entries
  for update to authenticated using (true) with check (true);

grant select, insert, update on public.damage_entries to authenticated;
grant usage, select on sequence public.damage_entries_id_seq to authenticated;
